"""Remove regenerated Python bytecode from a bundled camera runtime."""

from __future__ import annotations

import argparse
import os
import shutil
import zipfile
from pathlib import Path

LICENSE_ARCHIVE = "THIRD_PARTY_LICENSES.zip"


def _extended(path: Path) -> str:
    resolved = str(path.resolve())
    if os.name == "nt" and not resolved.startswith("\\\\"):
        return "\\\\?\\" + resolved
    return resolved


def prune_bytecode(runtime_root: Path) -> tuple[int, int]:
    """Remove only ``__pycache__`` trees and return removed files/bytes."""
    runtime_root = runtime_root.resolve()
    python_root = runtime_root / "python"
    if not python_root.is_dir():
        raise ValueError(f"runtime python directory is missing: {python_root}")

    cache_directories: list[Path] = []
    removed_files = 0
    removed_bytes = 0
    scan_root = _extended(python_root)
    for directory, names, files in os.walk(scan_root):
        directory_path = Path(directory)
        if directory_path.name.casefold() == "__pycache__":
            for filename in files:
                file_path = directory_path / filename
                removed_files += 1
                removed_bytes += os.stat(file_path).st_size
            names.clear()
            cache_directories.append(directory_path)

    for cache_directory in sorted(
        cache_directories,
        key=lambda value: len(value.parts),
        reverse=True,
    ):
        shutil.rmtree(str(cache_directory))

    return removed_files, removed_bytes


def archive_dist_info_licenses(runtime_root: Path) -> tuple[int, int]:
    """Preserve nested wheel licenses in one Windows-path-safe archive."""
    runtime_root = runtime_root.resolve()
    site_packages = runtime_root / "python" / "Lib" / "site-packages"
    if not site_packages.is_dir():
        raise ValueError(f"runtime site-packages directory is missing: {site_packages}")
    output = runtime_root / LICENSE_ARCHIVE
    if output.exists():
        raise ValueError(f"runtime license archive already exists: {output}")
    staging = output.with_suffix(f".staging-{os.getpid()}.zip")

    license_directories: list[Path] = []
    for directory, names, _ in os.walk(_extended(site_packages)):
        directory_path = Path(directory)
        if (
            directory_path.name.casefold() == "licenses"
            and directory_path.parent.name.casefold().endswith(".dist-info")
        ):
            names.clear()
            license_directories.append(directory_path)

    archived_files = 0
    archived_bytes = 0
    try:
        with zipfile.ZipFile(
            _extended(staging),
            "w",
            compression=zipfile.ZIP_DEFLATED,
            compresslevel=9,
        ) as archive:
            for license_directory in sorted(
                license_directories,
                key=lambda value: str(value).casefold(),
            ):
                files: list[Path] = []
                for directory, names, filenames in os.walk(str(license_directory)):
                    names.sort()
                    filenames.sort()
                    files.extend(Path(directory) / name for name in filenames)
                for file_path in files:
                    ordinary = Path(str(file_path).removeprefix("\\\\?\\"))
                    relative = ordinary.relative_to(site_packages).as_posix()
                    size = os.stat(str(file_path)).st_size
                    archive.write(str(file_path), arcname=relative)
                    archived_files += 1
                    archived_bytes += size
        os.replace(_extended(staging), _extended(output))
        for license_directory in sorted(
            license_directories,
            key=lambda value: len(value.parts),
            reverse=True,
        ):
            shutil.rmtree(str(license_directory))
    except Exception:
        if staging.exists():
            staging.unlink()
        raise

    return archived_files, archived_bytes


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--runtime-root", required=True, type=Path)
    args = parser.parse_args()
    license_files, license_bytes = archive_dist_info_licenses(args.runtime_root)
    removed_files, removed_bytes = prune_bytecode(args.runtime_root)
    print(
        f"Archived {license_files} license files ({license_bytes} bytes); "
        f"removed {removed_files} generated bytecode files ({removed_bytes} bytes)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
